services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitadvisor-bot-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fitness_advisor
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - postgres
    networks:
      - fitadvisor-network   

  postgres:
    image: postgres:15-alpine
    container_name: fitness-advisor-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: fitness_advisor
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d fitness_advisor"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - fitadvisor-network

volumes:
  postgres_data:
#  redis_data:

networks:
  fitadvisor-network:
    driver: bridge

#  redis:
#    image: redis:7-alpine
#    container_name: fitness-analytics-redis
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    networks:
#      - fitadvisor-network
